window.Langs = {
    active:                         "Aktif",
    address:                        "Alamat",
    applicant_list:                 "Daftar Pelamar",
    blog:                           "Blog",
    category:                       "Kategori",
    company:                        "Perusahaan",
    confirm:                        "Konfirmasi",
    content:                        "Isi",
    contract:                       "Kontrak",
    contract_duration:              "Durasi Kontrak",
    country:                        "Country",
    city:                           "Kota",
    date:                           "Tanggal",
    date_apply:                     "Tanggal Lamar",
    date_close:                     "Tanggal Tutup",
    date_join:                      "Tanggal Daftar",
    date_create:                    "Tanggal Dibuat",
    description:                    "Deskripsi",
    detail:                         "Detail",
    email:                          "Email",
    experience:                     "Pengalaman",
    failure:                        "Kesalahan",
    full_time:                      "Karyawan",
    inactive:                       "Tidak Aktif",
    industry:                       "Industri",
    info:                           "Info",
    job_list:                       "Daftar Lowongan",
    job_type:                       "Tipe Pekerjaan",
    location:                       "Lokasi",
    month_salary:                   "Gaji Bulanan",
    name:                           "Nama",
    noa:                            "Jml Pelamar",
    noj:                            "Jml Posisi",
    part_time:                      "Paruh Waktu",
    phone:                          "Telepon",
    publish:                        "Terpublis",
    reject:                         "Dibatalkan",
    registrant:                     "Registran",
    reg_name:                       "Nama Registran",
    reg_email:                      "Email Registran",
    requirement:                    "Persyaratan",
    seeker:                         "Seeker",
    show_applicant:                 "Tampilkan Pelamar",
    show_jobs:                      "Tampilkan Lowongan",
    statistic:                      "Statistik",
    status:                         "Status",
    success:                        "Berhasil",
    summary:                        "Ringkasan",
    tags:                           "Kata Kunci",
    title:                          "Judul",
    view_count:                     "Dibaca",
    views:                          "kali",
    
    btn_cancel:                     "Batal",
    btn_close:                      "Tutup",
    btn_create_new_blog:            "Buat Blog Baru",
    btn_delete:                     "Hapus",
    btn_edit:                       "Edit",
    btn_save:                       "Simpan",
    btn_save_change:                "Simpan Perubahan",
    btn_submit:                     "Kirim",
    btn_ok:                         "Oke",
    
    msg_client_invalid:             "Beberapa isian tidak benar.",
    msg_connect_failure:            "Koneksi server mengalami gangguan.",
    msg_server_error:               "Server mengalami masalah.",
    msg_sure_for_deletion:          "Yakin akan menghapus data ini?"
};

window.lang = function(line){
    return Langs.hasOwnProperty(line) ? Langs[line] : "~"+ line;
};
