window.Langs = {
    active:                         "Aktif",
    address:                        "Alamat",
    address_idcard:                 "Alamat KTP",
    applicant_list:                 "Daftar Pelamar",
    applied_job:                    "Lamaran Terkirim",
    blog:                           "Blog",
    category:                       "Kategori",
    company:                        "Perusahaan",
    company_name:                   "Nama Perusahaan",
    confirm:                        "Konfirmasi",
    content:                        "Isi",
    contract:                       "Kontrak",
    contract_duration:              "Durasi Kontrak",
    country:                        "Country",
    city:                           "Kota",
    date:                           "Tanggal",
    date_apply:                     "Tanggal Lamar",
    date_close:                     "Tanggal Tutup",
    date_create:                    "Tanggal Dibuat",
    date_join:                      "Tanggal Daftar",
    date_modified:                  "Tanggal Modifikasi",
    description:                    "Deskripsi",
    detail:                         "Detail",
    dob:                            "Tanggal Lahir",
    email:                          "Email",
    experience:                     "Pengalaman",
    failure:                        "Kesalahan",
    first_name:                     "Nama Depan",
    full_time:                      "Karyawan",
    gender:                         "Jenis Kelamin",
    gender_F:                       "Perempuan",
    gender_M:                       "Laki-laki",
    height:                         "Tinggi",
    id:                             "ID",
    ID:                             "ID",
    inactive:                       "Tidak Aktif",
    industry:                       "Industri",
    info:                           "Info",
    job_list:                       "Daftar Lowongan",
    job_type:                       "Tipe Pekerjaan",
    last_name:                      "Nama Belakang",
    location:                       "Lokasi",
    mf:                             "L/P",
    mf_F:                           "P",
    mf_M:                           "L",
    mobile:                         "No HP",
    month_salary:                   "Gaji Bulanan",
    name:                           "Nama",
    nationality:                    "Kewarganegaraan",
    no:                             "Tidak",
    noa:                            "Jml Pelamar",
    noj:                            "Jml Posisi",
    part_time:                      "Paruh Waktu",
    password:                       "Password",
    pending:                        "Pending",
    phone:                          "Telepon",
    pics:                           "Foto",
    pob:                            "Tempat Lahir",
    position:                       "Posisi",
    publish:                        "Terpublis",
    reject:                         "Dibatalkan",
    registrant:                     "Registran",
    reg_code:                       "Kode Registrasi",
    reg_email:                      "Email Registran",
    reg_name:                       "Nama Registran",
    reg_platform:                   "Platform Registr",
    reg_platform_id:                "ID Platform",
    religion:                       "Agama",
    requirement:                    "Persyaratan",
    role:                           "Role",
    searchable:                     "Mode Pencarian",
    seeker:                         "Seeker",
    show_applicant:                 "Tampilkan Pelamar",
    show_jobs:                      "Tampilkan Lowongan",
    specialization:                 "Spesialisasi",
    statistic:                      "Statistik",
    status:                         "Status",
    success:                        "Berhasil",
    summary:                        "Ringkasan",
    tags:                           "Kata Kunci",
    title:                          "Judul",
    update_status:                  "Update Status",
    view_count:                     "Dibaca",
    views:                          "kali",
    weight:                         "Berat",
    work_desc:                      "Deskripsi Pekerjaan",
    yes:                            "Ya",
    
    btn_cancel:                     "Batal",
    btn_close:                      "Tutup",
    btn_create_new_blog:            "Buat Blog Baru",
    btn_delete:                     "Hapus",
    btn_edit:                       "Edit",
    btn_save:                       "Simpan",
    btn_save_change:                "Simpan Perubahan",
    btn_submit:                     "Kirim",
    btn_ok:                         "Oke",
    
    error_404:                      "Halaman tidak ditemukan",
    
    msg_client_invalid:             "Beberapa isian tidak benar.",
    msg_connect_failure:            "Koneksi server mengalami gangguan.",
    msg_server_error:               "Server mengalami masalah.",
    msg_sure_for_deletion:          "Yakin akan menghapus data ini?"
};

window.lang = function(line){
    return Langs.hasOwnProperty(line) ? Langs[line] : "~"+ line;
};
