window.Langs = {
    active:                         "Aktif",
    address:                        "Alamat",
    blog:                           "Blog",
    company:                        "Perusahaan",
    confirm:                        "Konfirmasi",
    content:                        "Isi",
    country:                        "Country",
    city:                           "Kota",
    date:                           "Tanggal",
    date_join:                      "Tanggal Daftar",
    date_create:                    "Tanggal Dibuat",
    description:                    "Deskripsi",
    detail:                         "Detail",
    email:                          "Email",
    failure:                        "Kesalahan",
    inactive:                       "Tidak Aktif",
    industry:                       "Industri",
    info:                           "Info",
    name:                           "Nama",
    phone:                          "Telepon",
    registrant:                     "Registran",
    reg_name:                       "Nama Registran",
    reg_email:                      "Email Registran",
    seeker:                         "Seeker",
    show_jobs:                      "Lowongan",
    statistic:                      "Statistik",
    status:                         "Status",
    success:                        "Berhasil",
    summary:                        "Ringkasan",
    tags:                           "Kata Kunci",
    title:                          "Judul",
    view_count:                     "Dibaca",
    views:                          "kali",
    
    btn_cancel:                     "Batal",
    btn_close:                      "Tutup",
    btn_create_new_blog:            "Buat Blog Baru",
    btn_delete:                     "Hapus",
    btn_edit:                       "Edit",
    btn_save:                       "Simpan",
    btn_save_change:                "Simpan Perubahan",
    btn_submit:                     "Kirim",
    btn_ok:                         "Oke",
    
    msg_client_invalid:             "Beberapa isian tidak benar.",
    msg_connect_failure:            "Koneksi server mengalami gangguan.",
    msg_server_error:               "Server mengalami masalah.",
    msg_sure_for_deletion:          "Yakin akan menghapus data ini?"
};

window.lang = function(line){
    return Langs.hasOwnProperty(line) ? Langs[line] : "~"+ line;
};
